### ISSUE TITLE
UX improvements for the timeline view

### ISSUE THREAD

**Issue by MahatmaFatalError** [dalibo/pev2#146]
The timeline view is awesome, thanks for that! However, it stays a little bit behind its potential IMHO. Hence, here some improvement proposals:

1. The timeline diagram is somewhat constricted in the left view, thus hard to read. Can it be made a little bit bigger, e.g. via resizing the border between the left and the right view manually?
2. A duration X-axis with tick marks would be great to improve readability (when did an operation start, when did it end).
3. Adding an additional information dimension to the timeline, e.g. highlighting colors to depict e.g. the critical path, costs, rows etc. would help to spot and focus on potential root-causes in the plan.

Again, great work!

**Comment by gleu** [comment]
On the first item, I agree. A resizable border would be even better.

On the second item, it's almost impossible to do.

On the third item, IIRC, @pgiraud sticked to black&white to avoid distracting the user. IMO, the length of the bar is enough for me.

**Comment by pgiraud** [comment]
Let me complete the answer:

> 1. The timeline diagram is somewhat constricted in the left view, thus hard to read. Can it be made a little bit bigger, e.g. via resizing the border between the left and the right view manually?

I agree with you. Users should be able to resize the panels. I'll open a specific issue for this one.

> 2. A duration X-axis with tick marks would be great to improve readability (when did an operation start, when did it end).

I agree with you that it would be a nice improvement. Currently it's technically difficult because I simply rely on a simple HTML table to display the diagram (timeline). Having ticks would probably require using a library which I prefer to avoid for now.

> 3. Adding an additional information dimension to the timeline, e.g. highlighting colors to depict e.g. the critical path, costs, rows etc. would help to spot and focus on potential root-causes in the plan.

@gleu is right. During the development phase, I have tried using the highlighting colors to display the bars without success. I should try other options to highlight nodes.

**Comment by pgiraud** [comment]
With #180 the diagram pane is now resizeable.
I'm closing the current issue since I don't expect the 2 other points to be taken into account sometimes soon. I don't forget them however.
