### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by pgiraud** [dalibo/pev2#16]

**Comment by pgiraud** [comment]
See https://github.com/AlexTatiyants/pev/issues/42#issuecomment-509985745

@AbelVM I've done a lot on parallelism recently. It's merged and deployed. Can you please have a try and tell me what you think?

**Comment by AbelVM** [comment]
Love it. The deck effect instead of multiples nodes!!

I'd make it bolder when a node makes use of parallelism, not only the deck effect. This below is a bad design, but the idea would be to highlight that this is a parallel node with N workers running

![image](https://user-images.githubusercontent.com/9017165/63596981-b86a2b80-c5bc-11e9-942d-0d4c48c9c8ba.png)

**Comment by pgiraud** [comment]
In my opinion, the idea is to make the potential problems more obvious.
What would be the benefit of bringing the nodes using parallelism to the light, in your opinion? Though I can enhance their visibility, I don't them to be too prominent. Why do you mean by bolder?
Also, is it important in your option to visually determine the number of workers?

About the dots, it's indeed not a good idea to proceed like this because we can have an other node displayed on the right side.

![Capture du 2019-08-23 16-31-14](https://user-images.githubusercontent.com/319774/63600230-755f8680-c5c3-11e9-8187-1f04b7b4f308.png)

I'd be happy to enhance this information but I trying to prevent the interface to look like a christmas tree. ;-)
I'm open to any design suggestion though.
