### ISSUE TITLE
Display name of plan in tab title?

### ISSUE THREAD

**Issue by indy-singh** [dalibo/pev2#320]
Hi,

I use PEV2 pretty much every day, and name my plans. However, the name doesn't not display in the tab title.

Here I have three plans, but I have to cycle the tabs to find the plan that I want.
![current_before](https://user-images.githubusercontent.com/1906778/103292217-4f32cd80-49e5-11eb-9c51-716270dc4486.jpg)

With the title in the tab name, I can go straight into the tab that I am looking:-
![desired_after](https://user-images.githubusercontent.com/1906778/103292282-68d41500-49e5-11eb-98cd-d8a870fe2066.jpg)

Happy to send in a PR if welcome.

Thanks,
Indy

**Comment by pgiraud** [comment]
Thanks for the report. That's indeed something that should be fixed.
I expect to deploy a new version of the service with some minor additions. With this new version the plans will be automatically sent to server (shared) because it makes things a lot easier to manage. This will fix your issue.

**Comment by indy-singh** [comment]
Hi @pgiraud ,

That's great to hear.

> With this new version the plans will be automatically sent to server (shared) because it makes things a lot easier to manage.

Is this going to be opt-in? One of the reasons I use PEV2 so heavily is that it keeps everything in my local browser, and it only gets sent to the server if I choose to share. Will there be someway to manage the data that we send?

Thanks,
Indy

**Comment by pgiraud** [comment]
> Is this going to be opt-in?

No you won't have the choice. It will be sent everytime.

The reason why I want to change this and remove the "browser-only" mode of explain.dalibo.com is because I want to add a new feature that will allow people to share links with direct access to a specific node.

And for that, I actually would like to avoid confusion as much as possible. People are currently already confused and some users share links to plan that are stored locally (https://explain.dalibo.com/plan#).

From a usability point of view, as well as for the maintenance, it seems much easier to drop the support for the browser only submission of the plan.

I'm still studying the different alternatives though. I'm still not completely confident with this new approach. Also I don't want to loose users.

Did you know that for those who want to have a browser only version, it is possible to use PEV2 locally. There's a small application shipped with each release. One can download an archive in which there's an `index.html` file with some assets that can be simply run in the browser. This application doesn't save the list of plans though.


> Will there be someway to manage the data that we send?

For the new version of explain.dalibo.com, it will be easy to manage the plans from the list or from the plan page itself. The user who is sending the plan is then able to delete it.

What is the main reason why you want your plans not to be sent to the server? Is it because you don't trust other users and you're afraid that someone can find your plan by scanning the server and check every possible URL? Is it because you don't want your plan to be saved on any server?

What if it would be possible to protect your plans with a password?


Would you stop using explain.dalibo.com if it is doesn't let you use it locally? 

I'm trying to find the best solution for everyone. Your opinion is welcome.

**Comment by indy-singh** [comment]
> Did you know that for those who want to have a browser only version, it is possible to use PEV2 locally. There's a small application shipped with each release. One can download an archive in which there's an index.html file with some assets that can be simply run in the browser. This application doesn't save the list of plans though.

Yes, I've used a few times but I've always gone back to the browser based version because it saves my plans. Is it possible to update the local only version to write the plans to plans.json?

> The user who is sending the plan is then able to delete it.

How is this enforced? Can I create an account? Can plans be automatically deleted (TTL of 5 days etc). I like the model that pastebin.com offers (optionally sign in to manage pastes). I also like explain.depesz.com because it offers a one time delete link that I can save elsewhere.

> What is the main reason why you want your plans not to be sent to the server?

Abundance of caution. To easy to paste private information within a query plan. It's why I stopped using explain.depesz.com and moved to PEV2.

> Is it because you don't trust other users and you're afraid that someone can find your plan by scanning the server and check every possible URL?

If the plans could be enumerated then yes that would be a concern. But I'm assuming each plan will be given a securely randomly generated UUID.

> Is it because you don't want your plan to be saved on any server?

Yes.

> What if it would be possible to protect your plans with a password?

Then I have to remember my password. I would much prefer an optional "sign in with Google" to mange my plans (see pastebin.com model).

> Would you stop using explain.dalibo.com if it is doesn't let you use it locally?

No, I wouldn't stop using it. It is far too useful to stop using it :)

All in all, I wouldn't say this is a bad change, but it would be nice if there was some optional way in which I could manage my plans. Please note that none of the above of feature requests, just thinking out loud.

**Comment by indy-singh** [comment]
![image](https://user-images.githubusercontent.com/1906778/103536609-c0adc880-4e8a-11eb-871b-a60a0496c436.png)

Awesome!

I'm happy to close this issue, but I am interested in continuing the other discussion further :)

Thanks,
Indy

**Comment by pgiraud** [comment]
With your feedback, I decided to keep the behavior as is was before, ie. the plans are not send to the server unless you explicitely ask for it.

**Comment by indy-singh** [comment]
That's good to hear. I don't know how much work it is for PEV2 or how much traffic it gets but I'm only one person. It could be that sending it to the server is fine for 99% of people.

I don't want to discourage you from improving PEV2. It's an amazing tool.
