### ISSUE TITLE
Leak of user query

### ISSUE THREAD

**Issue by neissa** [dalibo/pev2#336]
You can try some random url and find some user SQL query.

https://explain.dalibo.com/plan/10
https://explain.dalibo.com/plan/20
https://explain.dalibo.com/plan/30
https://explain.dalibo.com/plan/40

a best random number with like 20 digit or password for the query could be nice

**Comment by pgiraud** [comment]
I understand your point.
This has already been reported in #319 by an other user.
FYI, I'm using the exact same method to randomize plan ids as in depesz.
I'll see what I can do though. Thanks for your feedback anyway.

**Comment by mjf** [comment]
Hello. What about to let users to choose between:
1. a generated **guess-proof** identifier (UUID or something similar),
2. some custom identifier (if there is no collision with already existing identifiers),
3. the current short and quite **memorizable** identifier (which I would personally let be the default method)?

**Comment by nightpool** [comment]
This has been reported by many users, and yet never fixed. Depesz has an option to anonymize plans, which I've always used, while Dalibo doesn't. I also never felt comfortable using Depesz unless it was absolutely necessary, but I was able to use Dalibo all of the time since it didn't share my plans with the server. Why not just make the very simple change to increase entropy?

**Comment by pgiraud** [comment]
Entropy of plan ids has been increased on explain.dalibo.com.
