### ISSUE TITLE
Local storage limits are hit easily

### ISSUE THREAD

**Issue by steelbrain** [dalibo/pev2#481]
Hello! Thank you for writing this. This has been very useful for some of the things I'm working on, but am running into limits when analysing large queries. Most browsers these days have a local storage quota of `5mb`, which is promptly hit.

I propose that alternative an storage system be incorporated to allow users to analyse larger queries. My go-to option is IndexedDB, which has a very convinient wrapper around it called idb-keyval (https://www.npmjs.com/package/idb-keyval) that has a reasonably similar (but async API) to localStorage.

What do you think?

**Comment by pgiraud** [comment]
Are you using pev2 directly or via explain.dalibo.com ?
With the latter, I would be surprised that you have on plan larger than 5mb. Instead I think you have a lot of plans saved (right column on the home page). I didn't reach the limit myself. An error message could be shown in this case.

Anyway, thanks for this proposal. It looks like a decent alternative. I'll have a look as soon as possible.

**Comment by steelbrain** [comment]
I am using it via explain.dalibo.com -- and the plan is actually quite large :)

It's an internal framework that collapses a lot of queries from individual components into one behemoth of a single query and executes and then hydrates the components with respective values. I found out I hit the limit by seeing the quota error in console from the browser. I tried it in Firefox, firefox config allows modification to quota values but was getting another error afterwards that I didn't dig too deep into

**Comment by pgiraud** [comment]
I would be interested to see what your plan look like (if you are allowed to share it). I'm afraid pev2 will not be able to handle such a big plan correctly.

Also have you tried pev2 the plan without explain.dalibo.com? See https://github.com/dalibo/pev2#portable-on-a-usb-stick

**Comment by Krysztophe** [comment]
I'd like to see this behemoth :smile:  I've played with thousands of partitions, it became very slow (#476) but I didn't get an error

**Comment by steelbrain** [comment]
Feast your eyes: https://gist.github.com/steelbrain/e57e508278a79ea4397efba9872b2b17

You may have to get the raw file as the gist inline limit doesn't load the entire file

**Comment by danwakefield** [comment]
I just had a similar issue but it appears to be due to `https://explain.dalibo.com/` itself.

https://github.com/dalibo/explain.dalibo.com/blob/2f3c61adee821c2bdcdffbf6e5730df382fca5b4/app/static/js/index.js#L64

stores the raw content directly into localstorage whereas PEV2 would detect, clean and reparse the JSON into a smaller repr

https://github.com/dalibo/pev2/blob/f2bc8341b84e33186c5fbfab0633f80054f6c7d3/src/services/plan-service.ts#L299

My workaround was to minimise the JSON before inputting it in the site.  

e.g The file in your gist goes from `5.8 M` to `230 K` using `cat queryplan.json | jq -c . > queryplan-compact.json` 

Unsure if the site could minfiy before storing it as it doesn't know if its getting a JSON plan or a text one before it hands off to PEV

**Comment by pgiraud** [comment]
Today, we deployed a new version of explain.dalibo.com. The plans are now automatically sent to server. The issue with the local storage being full should not happen anymore. Closing.
