### ISSUE TITLE
Size and position of nodes

### ISSUE THREAD

**Issue by lrweck** [dalibo/pev2#55]
This is more of a usability nitpick, but check this plan: https://pastebin.com/BFbcneeW

Some nodes get very far apart from each other, making reading complex queries very hard:

![image](https://user-images.githubusercontent.com/26086198/65543219-2325c400-dee7-11e9-9fdb-cfff6c0c206e.png)

![image](https://user-images.githubusercontent.com/26086198/65543363-6a13b980-dee7-11e9-8255-1f3cb2b4ca1b.png)

**Comment by pgiraud** [comment]
I unfortunately can't do anything with this easily. Not with the HTML structure I currently use.
This is because of the space used by the node children.
![Screenshot from 2019-09-25 16-21-52](https://user-images.githubusercontent.com/319774/65609818-afe88480-dfb0-11e9-86e5-6401fb5d2881.png)

I should have a try with left alignment to see what happens. I will get back to you if it works.

**Comment by pgiraud** [comment]
Left alignment doesn't help much.
Will consider this issue as "won't fix" since I can't think of a good way to address it.
